try:
	from PyGDB.PyGDB import *
except Exception as e:
	from PyGDB import *
